project:
  type: website

website:
  title: "Asymptotic Symmetries of dS and Inflation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Calculations"
        menu:
        - text: "Pure dS"
        - text: "Background"
          href: dS_background.qmd
        - text: "------"
      - about.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Pure dS"
        contents:
          - text: "Background"
            href: dS_background.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: false
  output: asis
